language: python
python:
    - "2.7"

# Setup anaconda
before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - which pip

install:
    - sudo apt-get -qq install build-essential libsuitesparse-dev
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib
    - source activate test-environment
    - conda install python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib cython
    - conda install python=$TRAVIS_PYTHON_VERSION coverage pylint
    - pip install -r requirements.txt

script:
    - python main_test.py

notifications:
    email: false
